apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-project
  namespace: argocd-apps
spec:
  description: Application Argo CD Project
  sourceRepos:
    - https://github.com/nagarajkrisjay/gitops-app.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
