apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-viewer
  namespace: argocd-apps
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
