apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-server-logs
  namespace: argocd-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-viewer
subjects:
- kind: ServiceAccount
  name: argocd-server
  namespace: argocd-apps
